// Generated by IcedCoffeeScript 108.0.11
(function() {
  var app;

  app = angular.module('Panels', []);

  app.directive('panelTools', function() {
    return {
      link: function(_, element) {
        return $('.btn', element).mousedown(function() {
          return $(this).css('top', '1px');
        }).mouseup(function() {
          return $(this).css('top', '');
        });
      },
      restrict: 'C'
    };
  });

}).call(this);
