// Generated by IcedCoffeeScript 108.0.11
(function() {
  var app;

  app = angular.module('TreeView', []);


  /*
  app.directive('tvParent', ->
  	{
  		link: (_, element) ->
  
  		restrict: 'C'
  	})
   */

  app.directive('tvToggle', function() {
    return {
      restrict: 'C',
      link: function(_, element) {
        return $(element).on('click', function() {
          $(this).next().slideToggle(115);
          return $(this).toggleClass('tv-open');
        });
      }
    };
  });

  app.directive('tvFolder', function() {
    return {
      restrict: 'E',
      replace: true,
      scope: {
        folder: '=value'
      },
      templateUrl: '/Templates/tvFolder.html',
      link: function(scope, element, attrib) {}
    };
  });

}).call(this);
